#!/usr/bin/env python3
"""Probe whether the target can dashboard the SOURCE's own ECS schema, and assert the traps.

    python3 verify-ecs-source.py --yes            # build the fixture, check, tear it down
    python3 verify-ecs-source.py --yes --mutate   # prove each check can actually fail
    python3 verify-ecs-source.py --yes --keep     # leave the fixture for inspection

THIS SCRIPT WRITES TO THE TARGET, WHICH NOTHING ELSE IN THIS DIRECTORY DOES. It creates one
table and one view (both prefixed `kb2cs_ecs_probe`), registers two sources, and deletes all
four on the way out -- including after a failure. `--yes` is required so that cannot happen by
accident against a customer's cluster. Nothing existing is read, modified or dropped.

WHY A FIXTURE RATHER THAN THE CUSTOMER'S OWN ROWS
-------------------------------------------------
The question is what the TARGET does to an ECS-shaped table, so the expected answers must not
come from the target. Here they are arithmetic: the fixture's values are generated by a
closed-form expression, so every expectation is computed in Python and the target is never
asked to confirm its own output. That also makes the script portable -- it needs no
Elasticsearch, no corpus, and no migrated dashboard.

WHAT IT ESTABLISHES, AND WHY IT IS WORTH A SCRIPT
-------------------------------------------------
A customer who keeps Filebeat/Metricbeat for a proof of concept lands ECS documents, not OTel
ones. A `log` source can be pointed straight at them -- `references/sources.md` has the
measured detail -- but Beats writes ONE DOCUMENT PER METRICSET, so a table holding several
metricsets is mostly NULL, and:

    the target's builder aggregations read a NULL as a ZERO.

So `avg` is divided by the number of rows sharing the group, and `min` and `last_value`
collapse to 0. Which aggregations this ruins is NOT uniform, and guessing it wrong in either
direction is easy: `max` and `sum` come out right because zero is their identity, and
`count_distinct` comes out right because it is the one numeric aggregation that is NOT
coerced. `count` is wrong for a third reason -- it counts rows, and the other metricsets'
documents are rows. Every one of them renders `status=ok, hasData=true`. That is the trap
this file asserts rather than remembers: if a future ClickStack stops coercing, these checks
go red and the reference prose is wrong.

The dilution factor is deliberately NOT the number of metricsets in the fixture. It is four
with three metricsets, because the network metricset emits one document per interface. Fitting
it to the metricset count is a mistake that reproduces the right number on a corpus where
every metricset happens to emit one row -- so the fixture encodes the difference.
"""
import hashlib
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import conf  # noqa: E402  endpoints and credentials, all environment-driven
import mcp as cs  # noqa: E402  the MCP-over-plain-HTTP helper, same directory

G, R, Y, B, X = "\033[32m", "\033[31m", "\033[90m", "\033[1m", "\033[0m"
_state = {"pass": 0, "fail": 0, "quiet": False}

# ---------------------------------------------------------------------------- the fixture
# Flat dotted columns, no attribute Map anywhere -- how ECS actually lands when it is not
# reshaped. The column TYPES are what a customer gets from a typed load; the string column
# below is what the sanctioned Vector/VRL route lands instead.
COLUMN_TYPES = {
    "@timestamp": "DateTime64(3)",
    "host.name": "LowCardinality(String)",
    "event.dataset": "LowCardinality(String)",
    "probe.net.name": "LowCardinality(String)",
    "probe.cpu.pct": "Nullable(Float64)",
    "probe.mem.pct": "Nullable(Float64)",
    "probe.net.in.bytes": "Nullable(Float64)",
    # The same cpu value as TEXT. Not decoration: the documented Filebeat/Metricbeat -> Vector
    # route converts ECS to OTel in VRL and flattens every field to a string, so a customer on
    # the sanctioned path gets this column type, not Float64. One tick carries 'n/a' to stand
    # for the non-numeric values a real flattening produces.
    "probe.cpu.pct.str": "String",
    # An OTel-shaped attribute map, because the coercion below is NOT an ECS problem. A
    # migrated tile that averages `LogAttributes['x']` where some rows lack the key hits it
    # just as hard: ClickHouse returns '' for a missing Map key, and '' casts to a counting
    # zero exactly like a NULL does.
    "attrs": "Map(LowCardinality(String), String)",
}

NOT_NUMERIC = "n/a"        # what tick 0 of the string column holds

# The table name carries a fingerprint of the schema above, and that is not cosmetic: the
# target CACHES a table's column list BY NAME (asserted below), so a fixture that changed
# shape under a stable name would be described with its previous columns and this file would
# report a target bug that is really a stale cache. Changing COLUMN_TYPES renames the table.
_FINGERPRINT = hashlib.sha1(repr(sorted(COLUMN_TYPES.items())).encode()).hexdigest()[:8]
TABLE = "kb2cs_ecs_probe_" + _FINGERPRINT
VIEW = TABLE + "_cpu"
HOSTS = ["probe-a", "probe-b", "probe-c"]
TICKS = 20
BASE = "2026-01-05 00:00:00"            # fixed, so the run does not depend on the wall clock
FROM_ISO, TO_ISO = "2026-01-05T00:00:00Z", "2026-01-05T00:30:00Z"
IFACES = ["eth0", "lo"]

CPU = "`probe.cpu.pct`"
MEM = "`probe.mem.pct`"
NET = "`probe.net.in.bytes`"

# One document per metricset per tick, network once per interface -- the shape Beats writes.
ROWS_PER_TICK = 2 + len(IFACES)          # cpu + mem + one per interface = 4
N_METRICSETS = 3                         # and this is 3: the two are not the same number
STEP = 0.003                             # the cpu value grid, which sets the quantile tolerance


def cpu_values(h):
    """The fixture's cpu series for host index `h`, as three-decimal values above zero.

    Above zero on purpose: a `min` that collapses to the injected zero is only detectable if
    no real value is zero."""
    return [round(0.100 + STEP * i + 0.010 * h, 3) for i in range(TICKS)]


def mem_values(h):
    return [round(0.400 + 0.002 * i + 0.005 * h, 3) for i in range(TICKS)]


def net_value(h, i, j):
    """A monotonic counter, per host and per interface, as a real counter would be."""
    return 1000000 * (h + 1) + 5000 * i + 777 * j


def quantile(vals, q):
    """Linear interpolation on the sorted values at rank q*(n-1).

    The convention both platforms were measured to use: on the reference corpus Elastic's
    `percentiles` and the target's `quantile` agreed to the last digit on 60 samples. A
    failure of the quantile check therefore means the target's convention CHANGED, which is
    worth being told about rather than absorbing into a loose tolerance."""
    s = sorted(vals)
    pos = q * (len(s) - 1)
    lo = int(pos)
    if lo + 1 >= len(s):
        return s[-1]
    return s[lo] + (pos - lo) * (s[lo + 1] - s[lo])


def rows():
    """One row as (timestamp, host, dataset, iface, cpu, mem, net, cpu-as-text, attrs)."""
    out = []
    for h, host in enumerate(HOSTS):
        cpu, mem = cpu_values(h), mem_values(h)
        for i in range(TICKS):
            base = i * 60
            # The offsets inside the tick are what make `last_value` deterministic: the newest
            # row for a host is always a network document, so an unscoped last_value on the
            # cpu column has to reach across metricsets and read the coerced zero.
            # The map key rides on the cpu documents only -- the same sparsity as a real
            # attribute that one dataset sets and another does not.
            out.append((base + 0, host, "probe.cpu", "", cpu[i], None, None,
                        NOT_NUMERIC if i == 0 else repr(cpu[i]),
                        "map('cpu_pct', '%s')" % cpu[i]))
            out.append((base + 10, host, "probe.mem", "", None, mem[i], None, "", "map()"))
            for j, iface in enumerate(IFACES):
                out.append((base + 20 + j, host, "probe.net", iface,
                            None, None, net_value(h, i, j), "", "map()"))
    return out


DDL = "CREATE TABLE {db}.{tbl} (%s) ENGINE = MergeTree ORDER BY (`event.dataset`, `@timestamp`)" % (
    ", ".join("`%s` %s" % (k, v) for k, v in COLUMN_TYPES.items()))

VIEW_DDL = """
CREATE VIEW {db}.{view} AS
SELECT `@timestamp`, `host.name`, `event.dataset`, `probe.cpu.pct`
FROM {db}.{tbl} WHERE `event.dataset` = 'probe.cpu'
"""


def build():
    """Create the fixture. Returns nothing; raises if the target rejects it."""
    db = conf.CH_DATABASE
    conf.ch_statement("DROP TABLE IF EXISTS %s.%s" % (db, TABLE))
    conf.ch_statement("DROP VIEW IF EXISTS %s.%s" % (db, VIEW))
    conf.ch_statement(DDL.format(db=db, tbl=TABLE))
    vals = []
    for off, host, ds, iface, cpu, mem, net, text, attrs in rows():
        vals.append("(toDateTime64('%s', 3) + %d, '%s', '%s', '%s', %s, %s, %s, '%s', %s)"
                    % (BASE, off, host, ds, iface,
                       "NULL" if cpu is None else repr(cpu),
                       "NULL" if mem is None else repr(mem),
                       "NULL" if net is None else repr(net), text, attrs))
    conf.ch_statement("INSERT INTO %s.%s VALUES %s" % (db, TABLE, ",".join(vals)))
    conf.ch_statement(VIEW_DDL.format(db=db, tbl=TABLE, view=VIEW))


def teardown(sources):
    for sid in sources:
        if sid:
            cs.call("clickstack_delete_source", {"id": sid})
    db = conf.CH_DATABASE
    for stmt in ("DROP VIEW IF EXISTS %s.%s" % (db, VIEW),
                 "DROP TABLE IF EXISTS %s.%s" % (db, TABLE)):
        try:
            conf.ch_statement(stmt)
        except conf.QueryError as exc:
            print(f"  {R}bad{X}  could not drop: {exc}")


# ---------------------------------------------------------------------------- reporting
def ok(m):
    if not _state["quiet"]:
        print(f"  {G}ok{X}   {m}")
    _state["pass"] += 1


def bad(m):
    if not _state["quiet"]:
        print(f"  {R}bad{X}  {m}")
    _state["fail"] += 1


def note(m):
    if not _state["quiet"]:
        print(f"  {Y}note{X} {m}")


def hdr(m):
    if not _state["quiet"]:
        print(f"\n{B}{m}{X}")


# ---------------------------------------------------------------------------- mutations
# A check that cannot be made to fail is not a check. These perturb what the probe ASKS the
# target, so a correct target stops matching expectations that are still correct.
MUT = {}

MUTATIONS = [
    ("read the mem column where the expectation was computed for cpu", {"swap_column": True}),
    ("drop the dataset predicate from the scoped checks", {"drop_predicate": True}),
    ("query the sparse table where the check expects the dense view", {"dense_is_sparse": True}),
    ("take the dilution to be the metricset count instead of the row count",
     {"dilution_is_metricsets": True}),
    ("shift the quantile expectation by one rank", {"quantile_off_by_one": True}),
    ("skip the ALTER, so the column the cache checks describe never exists",
     {"skip_alter": True}),
]


def cpu_col():
    return MEM if MUT.get("swap_column") else CPU


def scope(dataset):
    """The predicate a faithful tile must carry. The mutation drops it, which is the whole
    point of the trap: a tile is one missing clause away from being wrong and still green."""
    if MUT.get("drop_predicate"):
        return None
    return "`event.dataset` = '%s'" % dataset


def dilution():
    return N_METRICSETS if MUT.get("dilution_is_metricsets") else ROWS_PER_TICK


# ---------------------------------------------------------------------------- querying
def tbl(source_id, select, where=None, lang="sql", group="`host.name`"):
    """One `clickstack_table` call, returned as {group value: {alias: value}}."""
    args = {"sourceId": source_id, "startTime": FROM_ISO, "endTime": TO_ISO,
            "select": select}
    if group:
        args["groupBy"] = group
    if where:
        args["where"] = where
        args["whereLanguage"] = lang
    res = cs.call("clickstack_table", args)
    if not isinstance(res, dict) or "result" not in res:
        # Do not raise: a tile whose expression does not compile is one of the outcomes
        # being checked, so it has to be reportable rather than fatal.
        return {"__error__": json.dumps(res)[:200]}
    out = {}
    for row in res["result"]["data"]:
        key = row.get("host.name") if group else ""
        out[key] = row
    return out


def near(got, want, tol):
    return got is not None and abs(float(got) - want) <= tol


def per_host(label, got, expected, tol=0.0):
    """Assert one value per fixture host, so a check covers three series rather than one."""
    if "__error__" in got:
        bad("%s  (the query did not compile: %s)" % (label, got["__error__"]))
        return
    wrong = [(h, expected[i], got.get(h, {}).get("v"))
             for i, h in enumerate(HOSTS)
             if not near(got.get(h, {}).get("v"), expected[i], tol)]
    if wrong:
        h, w, g = wrong[0]
        bad("%s  (%s: expected %r, target says %r)" % (label, h, w, g))
    else:
        ok(label)


# ---------------------------------------------------------------------------- the checks
def run(quiet=False):
    _state.update({"pass": 0, "fail": 0, "quiet": quiet})
    db = conf.CH_DATABASE
    conn = None
    sparse = dense = None
    try:
        build()
        listing = cs.call("clickstack_list_sources", {})
        conn = listing["connections"][0]["id"]

        # ---------------------------------------------------- structural: is it accepted?
        hdr("Can a source be pointed at flat ECS columns at all?")
        common = {"kind": "log", "connection": conn, "databaseName": db,
                  "timestampValueExpression": "`@timestamp`",
                  "bodyExpression": "`event.dataset`",
                  "section": "kb2cs probe"}
        made = cs.call("clickstack_save_source", dict(
            common, name="kb2cs probe (wide ECS)", tableName=TABLE,
            defaultTableSelectExpression="`@timestamp`, `host.name`, `event.dataset`"))
        sparse = made.get("id")
        if sparse:
            ok("`kind: log` accepts a table of flat dotted ECS columns, no attribute Map")
        else:
            bad("save_source rejected the wide ECS table: %s" % json.dumps(made)[:200])
            return _state["pass"], _state["fail"]

        made = cs.call("clickstack_save_source", dict(
            common, name="kb2cs probe (dense view)", tableName=VIEW,
            defaultTableSelectExpression="`@timestamp`, `host.name`, `probe.cpu.pct`"))
        dense = made.get("id")
        if dense:
            ok("a ClickHouse VIEW is accepted as a source table -- no second copy of the data")
        else:
            bad("save_source rejected the view: %s" % json.dumps(made)[:200])

        desc = cs.call("clickstack_describe_source", {"sourceId": sparse})
        seen = {c["name"]: c["type"] for c in desc.get("source", {}).get("columns", [])}
        missing = {k: (v, seen.get(k)) for k, v in COLUMN_TYPES.items() if seen.get(k) != v}
        if missing:
            bad("describe_source misreports %d column(s), expected vs seen: %s"
                % (len(missing), missing))
        else:
            ok("describe_source reports all %d dotted columns with the declared types"
               % len(COLUMN_TYPES))

        # ---------------------------------------------------- the schema cache, asserted
        # Found by being misled by it: a fixture recreated with one extra column was still
        # described with its previous columns, which reads exactly like the target dropping a
        # column. It is a cache keyed by table name, and it matters for a proof of concept,
        # where the landing schema is iterated on. Asserted deliberately so that ClickStack
        # fixing it turns this red rather than passing silently.
        hdr("Column discovery is cached by table name")
        if not MUT.get("skip_alter"):
            conf.ch_statement(
                "ALTER TABLE %s.%s ADD COLUMN `probe.added.later` Float64 DEFAULT 7"
                % (db, TABLE))
        again = cs.call("clickstack_describe_source", {"sourceId": sparse})
        after = {c["name"] for c in again.get("source", {}).get("columns", [])}
        if "probe.added.later" in after:
            bad("describe_source noticed a column added after the first describe -- "
                "the cache is gone, so update references/sources.md")
        else:
            ok("a column added after the first describe is NOT reported (stale by name)")
        probe = tbl(sparse, [{"aggFn": "max", "valueExpression": "`probe.added.later`",
                              "alias": "v"}])
        per_host("but a tile can still READ it -- the cache misleads discovery, not querying",
                 probe, [7.0] * len(HOSTS), 1e-12)

        # ------------------------------------------- the trap: a sparse table, unscoped
        hdr("A wide Beats-shaped table, queried the way a migrated panel would be (no scope)")
        note("%d rows share each (host) group; only %d of them carry the cpu field"
             % (ROWS_PER_TICK * TICKS, TICKS))
        col = cpu_col()
        got = tbl(sparse, [
            {"aggFn": "avg", "valueExpression": col, "alias": "v"}])
        per_host("avg is diluted by exactly the row count, not the metricset count",
                 got, [sum(cpu_values(h)) / (TICKS * dilution()) for h in range(len(HOSTS))],
                 1e-12)

        got = tbl(sparse, [{"aggFn": "min", "valueExpression": col, "alias": "v"}])
        per_host("min collapses to 0 -- the injected zero is the smallest value",
                 got, [0.0] * len(HOSTS))

        got = tbl(sparse, [{"aggFn": "last_value", "valueExpression": col, "alias": "v"}])
        per_host("last_value collapses to 0 -- the newest row is another metricset's",
                 got, [0.0] * len(HOSTS))

        got = tbl(sparse, [{"aggFn": "count", "alias": "v"}])
        per_host("count returns every metricset's rows, not the panel's",
                 got, [TICKS * dilution()] * len(HOSTS))

        got = tbl(sparse, [{"aggFn": "max", "valueExpression": col, "alias": "v"}])
        per_host("max survives -- zero cannot win a maximum over positive values",
                 got, [max(cpu_values(h)) for h in range(len(HOSTS))], 1e-12)

        got = tbl(sparse, [{"aggFn": "sum", "valueExpression": col, "alias": "v"}])
        per_host("sum survives -- zero is its identity",
                 got, [sum(cpu_values(h)) for h in range(len(HOSTS))], 1e-9)

        # Not a blanket coalesce: this one aggregation is left alone, so "NULL reads as zero"
        # is the wrong mental model to carry away. It has to be checked per aggregation.
        got = tbl(sparse, [{"aggFn": "count_distinct", "valueExpression": col, "alias": "v"}])
        per_host("count_distinct survives -- it is NOT coerced, unlike avg/min/last_value",
                 got, [TICKS] * len(HOSTS), 0)

        # The coercion happens outside the value expression, so it cannot be written around:
        # returning NULL for the rows you want excluded still yields a zero. The predicate is
        # the fix, and this is what rules out the cheaper-looking alternative.
        guarded = ("if(`event.dataset` = 'probe.cpu', %s, NULL)"
                   % (MEM if MUT.get("swap_column") else CPU))
        got = tbl(sparse, [{"aggFn": "avg", "valueExpression": guarded, "alias": "v"}])
        per_host("emitting NULL from the value expression does NOT avoid the coercion",
                 got, [sum(cpu_values(h)) / (TICKS * dilution()) for h in range(len(HOSTS))],
                 1e-12)

        # The mechanism, not just the symptom. The target compiles a numeric aggregation as
        # AVG(toFloat64OrDefault(toString(col))) -- read off an "Unknown expression" error it
        # echoed back. That single expression explains the whole table above: toString(NULL)
        # is NULL, toFloat64OrDefault yields its default for anything it cannot parse, and
        # count_distinct escapes because it never goes through the cast. Asserting the shape
        # rather than the symptom is what makes a future change to it legible.
        mech = conf.ch_query(
            "SELECT `host.name` AS h, avg(toFloat64OrDefault(toString(%s))) AS v "
            "FROM %s.%s WHERE `@timestamp` >= toDateTime64('%s', 3) "
            "AND `@timestamp` <= toDateTime64('%s', 3) + 1800 GROUP BY h ORDER BY h"
            % (col, db, TABLE, BASE, BASE))
        by_host = {r[0]: {"v": r[1]} for r in mech["data"]}
        per_host("the coercion is exactly avg(toFloat64OrDefault(toString(x)))",
                 by_host, [sum(cpu_values(h)) / (TICKS * ROWS_PER_TICK)
                           for h in range(len(HOSTS))], 1e-12)

        # ------------------------------------------- the same trap on an OTel-shaped map
        hdr("A missing MAP KEY, which is the OTel-shaped version of the same trap")
        note("nothing ECS about this one -- it is what a migrated tile over "
             "LogAttributes['x'] does when some rows lack the key")
        attr = "attrs['cpu_pct']"
        per_host("averaging a map attribute absent on some rows is diluted the same way",
                 tbl(sparse, [{"aggFn": "avg", "valueExpression": attr, "alias": "v"}]),
                 [sum(cpu_values(h)) / (TICKS * dilution()) for h in range(len(HOSTS))],
                 1e-9)
        per_host("and the same predicate restores it",
                 tbl(sparse, [{"aggFn": "avg", "valueExpression": attr, "alias": "v"}],
                     scope("probe.cpu")),
                 [sum(cpu_values(h)) / TICKS for h in range(len(HOSTS))], 1e-9)

        # ------------------------------------------- the string-typed case Vector produces
        hdr("The same metric as a STRING column, which is what the Vector/VRL route lands")
        strcol = "`probe.cpu.pct.str`"
        parses = [v for v in cpu_values(0)][1:]     # tick 0 holds 'n/a' on every host
        got = tbl(sparse, [{"aggFn": "avg", "valueExpression": strcol, "alias": "v"}],
                  scope("probe.cpu"))
        per_host("a numeric metric stored as text still aggregates -- the cast parses it",
                 got, [sum(cpu_values(h)[1:]) / TICKS for h in range(len(HOSTS))], 1e-12)
        note("but note the denominator: the %r tick contributed a 0, not an exclusion"
             % NOT_NUMERIC)
        got = tbl(sparse, [{"aggFn": "avg", "valueExpression": strcol, "alias": "v"}],
                  "%s AND %s != '%s'" % (scope("probe.cpu") or "1=1", strcol, NOT_NUMERIC))
        per_host("excluding the non-numeric rows by predicate restores the true average",
                 got, [sum(cpu_values(h)[1:]) / (TICKS - 1) for h in range(len(HOSTS))], 1e-12)

        # ------------------------------------------- the fix: carry the dataset predicate
        hdr("The same table with the metricset predicate every tile must carry")
        where = scope("probe.cpu")
        for agg, label, expected, tol in [
            ("avg", "avg is faithful",
             [sum(cpu_values(h)) / TICKS for h in range(len(HOSTS))], 1e-12),
            ("min", "min is faithful",
             [min(cpu_values(h)) for h in range(len(HOSTS))], 1e-12),
            ("max", "max is faithful",
             [max(cpu_values(h)) for h in range(len(HOSTS))], 1e-12),
            ("last_value", "last_value is faithful",
             [cpu_values(h)[-1] for h in range(len(HOSTS))], 1e-12),
            ("count", "count is the metricset's own row count",
             [TICKS] * len(HOSTS), 0),
            ("count_distinct", "count_distinct is faithful, as it already was unscoped",
             [TICKS] * len(HOSTS), 0),
        ]:
            item = {"aggFn": agg, "alias": "v"}
            if agg != "count":
                item["valueExpression"] = col
            per_host(label, tbl(sparse, [item], where), expected, tol)

        # The quantile is the one aggregation whose wrong answer looks plausible: with this
        # dilution an unscoped p95 silently reports the real p80. Tolerance is half the value
        # grid, which is what distinguishes one rank from the next -- not a fitted number.
        off = 1 if MUT.get("quantile_off_by_one") else 0
        want = [quantile(cpu_values(h), 0.95) + off * STEP for h in range(len(HOSTS))]
        per_host("quantile is faithful, and to the same interpolation as Elastic's",
                 tbl(sparse, [{"aggFn": "quantile", "level": 0.95,
                               "valueExpression": col, "alias": "v"}], where),
                 want, STEP / 2)

        # ------------------------------------------- the better fix: one view per metricset
        hdr("A view per metricset -- the same questions with no predicate at all")
        src = sparse if MUT.get("dense_is_sparse") else dense
        for agg, label, expected in [
            ("avg", "avg", [sum(cpu_values(h)) / TICKS for h in range(len(HOSTS))]),
            ("min", "min", [min(cpu_values(h)) for h in range(len(HOSTS))]),
            ("last_value", "last_value", [cpu_values(h)[-1] for h in range(len(HOSTS))]),
            ("count", "count", [TICKS] * len(HOSTS)),
        ]:
            item = {"aggFn": agg, "alias": "v"}
            if agg != "count":
                item["valueExpression"] = col
            per_host("%s needs no discipline on a dense source" % label,
                     tbl(src, [item]), expected, 1e-12)

        # ------------------------------------------- the query surface
        hdr("What a tile can express against ECS column names")
        got = tbl(sparse, [{"aggFn": "count", "alias": "v"}],
                  "event.dataset:probe.cpu", lang="lucene")
        per_host("a Lucene filter resolves a DOTTED column name, with no Map involved",
                 got, [TICKS] * len(HOSTS), 0)

        # A counter has no builder shape: `increase` is metric-source-only, and a Gauge-style
        # avg over a cumulative counter is meaningless. This is the SQL a tile has to carry.
        sql = ("SELECT host, sum(delta) AS v FROM ("
               "  SELECT `host.name` AS host, `probe.net.name` AS iface,"
               "         max({net}) - min({net}) AS delta"
               "  FROM {db}.{tbl}"
               "  WHERE `event.dataset` = 'probe.net' AND $__timeFilter_ms(`@timestamp`)"
               "  GROUP BY host, iface"
               ") GROUP BY host ORDER BY host LIMIT 100").format(
                   net=NET, db=db, tbl=TABLE)
        res = cs.call("clickstack_sql", {"connectionId": conn, "sql": sql,
                                         "startTime": FROM_ISO, "endTime": TO_ISO})
        counter = {r["host"]: {"v": r["v"]} for r in res.get("result", {}).get("data", [])}
        rise = len(IFACES) * 5000 * (TICKS - 1)      # each interface climbs by 5000 a tick
        per_host("a SQL tile de-cumulates a counter per interface and totals it", counter,
                 [rise] * len(HOSTS), 0)

        return _state["pass"], _state["fail"]
    finally:
        if not MUT and not _state["quiet"]:
            hdr("Tearing the fixture down")
        if "--keep" in sys.argv:
            if not _state["quiet"]:
                note("--keep: left %s.%s, %s.%s and 2 sources in place" % (db, TABLE, db, VIEW))
        else:
            teardown([sparse, dense])
            if not _state["quiet"]:
                ok("fixture removed: 2 sources, 1 view, 1 table")


def mutate_suite():
    print(f"\n{B}Mutation test: each mutation must turn at least one check red{X}")
    base_p, base_f = run(quiet=True)
    print(f"  {Y}note{X} baseline: {base_p} pass, {base_f} fail")
    if base_f:
        print(f"  {R}bad{X}  baseline is not clean; fix that before trusting the mutations")
        return 1
    silent = 0
    for desc, flags in MUTATIONS:
        MUT.clear()
        MUT.update(flags)
        p, f = run(quiet=True)
        if f:
            print(f"  {G}fires{X}  {desc}  ({f} check(s) red)")
        else:
            print(f"  {R}SILENT{X} {desc}  -- the check does not catch this")
            silent += 1
    MUT.clear()
    return silent


if __name__ == "__main__":
    if "--yes" not in sys.argv:
        print(__doc__)
        sys.exit("refusing to run without --yes: this script CREATES a table in %s"
                 % conf.CH_DATABASE)
    print(conf.describe())
    if "--mutate" in sys.argv:
        sys.exit(1 if mutate_suite() else 0)
    p, f = run()
    print()
    if f == 0:
        print(f"{G}{p} checks passed.{X} The target reads NULL as zero; scope every tile.")
    else:
        print(f"{R}{f} check(s) failed.{X} ({p} passed) -- "
              "if the aggregation checks moved, references/sources.md is now wrong")
    print()
    sys.exit(f)
